### ISSUE TITLE
Tuning parameters for marine data

### ISSUE THREAD

**Issue by DaloroAT** [DaloroAT/first_break_picking#14]
https://github.com/DaloroAT/first_breaks_picking/issues/9#issuecomment-1579492537

https://github.com/DaloroAT/first_breaks_picking/issues/9#issuecomment-1581470104

**Comment by DaloroAT** [comment]
Hello @kerim371

Let's discuss tuning of parameters in new issue with correspondence name. It could be useful for other users if they meet the same problem.

**Comment by DaloroAT** [comment]
You can try traces-per-gather=20 and gain=2 or 3 for your marine data.

**Comment by kerim371** [comment]
Right, gain 2 and trace per gather 20 greatly improves the result:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/eecb2fcf-d0f6-4b40-8ce0-1d365c40d369)

And gain 2, trc per gath 60:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/2f666cf6-a4f1-4d01-90e5-9c58f995f676)

**Comment by DaloroAT** [comment]
Great! You can also try -2 or -3.

**Comment by kerim371** [comment]
By the way this dataset is freely available: [Viking Graben line 12](https://wiki.seg.org/wiki/Mobil_AVO_viking_graben_line_12)
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/86a2c133-63b2-4c9c-b3f3-b6d6f323a458)

**Comment by DaloroAT** [comment]
Thank you! I will update examples later
