### ISSUE TITLE
Testing on land data

### ISSUE THREAD

**Issue by kerim371** [DaloroAT/first_break_picking#15]
I tried to run this on 2 different land datasets.

Fisrt one has pretty good signal/noise ratio and the algorithm works pretty good:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/cd02a8e4-24f4-475f-9310-88ee30a91bb6)

The second dataset is of poor quality: geology includes permafrost with high energy attenuation, surface noise is high:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/97d7bd09-0b62-46be-86f7-0012676869cb)

Do you have ideas what we can do to improve the result of the second dataset?

**Comment by DaloroAT** [comment]
You have so much traces on second dataset, how much time did you wait?

**Comment by DaloroAT** [comment]
In general for very noisy data you should increase traces-per-gather, decrease maximum time and keep gain ~1-2.

You can try maximum time 1200 ans tps 40 if number of traces is dividable by 40.

**Comment by kerim371** [comment]
Yes its about 13k traces and it took about 10-20 minuts, don't know exactly.
It is 2D seismic that contains 70k traces overall.

**Comment by kerim371** [comment]
Does the perfomance is pretty slow because of python? or how do you think can we improve the algorithm so it works abou 10 time faster? for example by using julia instead of python.

**Comment by DaloroAT** [comment]
No, it's not python problem. There are lot of ways how to improve performance. One of the simplest way - use GPU. Do you have GPU?

Right now it's just demo or first version. I don't want to spend a lot of efforts on optimisation if no one use the library 🥲

**Comment by kerim371** [comment]
> Right now it's just demo or first version. I don't want to spend a lot of efforts on optimisation if no one use the library 🥲

I think this this repo has a potential.

I think I have GPU but I haven't worked with it.
NVIDIA GeForce RTX 3050 GPU, I used to check whether it support CUDA and it seems so.

How I try with GPU?

**Comment by DaloroAT** [comment]
Yes, it supports cuda. You are not able to use GPU with repo right now. But I will add possibility after I return fron Vienna. Probably it will be on Friday.
