### ISSUE TITLE
Error Loading SEGY

### ISSUE THREAD

**Issue by HHTC0** [DaloroAT/first_break_picking#17]
Hi,

Thank you for sharing this with us.

I receive the error **** after I selected SGY file.

Also, it breaks my Anaconda installation after I install the library and I have reinstalled.

Some other error message I received when I installed the library are below. I installed these libraries afterwards and then reinstalled the main library. But still the same error message as above.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
conda-repo-cli 1.0.41 requires requests_mock, which is not installed.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
conda-repo-cli 1.0.41 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
conda-repo-cli 1.0.41 requires nbformat==5.4.0, but you have nbformat 5.7.0 which is incompatible.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.41 requires requests==2.28.1, but you have requests 2.28.2 which is incompatible.

**Comment by HHTC0** [comment]
Error

setWidth(self, width: int): argument 1 has unexpected type 'float

**Comment by HHTC0** [comment]
Solved - I downgraded by Python to 3.8.6 and installed the libraries exactly as listed under required and able to get the Desktop application work through command prompt.

**Comment by DaloroAT** [comment]
Hello @HHTC0 
Unfortunately, I wasn't able to reply earlier.
Yep, you should follow the requirements of the projects, otherwise, you could get errors, especially if external libraries lose backward compatibility.
Btw, have you tried to install it with other versions of Python and with an exact list of requirements?

**Comment by HHTC0** [comment]
Hi @DaloroAT,

No worries. I tried on 3.10 and 3.11. However, no success and would get that error which I mentioned above.

I am Borehole Geophysicist and would love to have below functionalities in it for VSP data pre processing.

1. Manual Time Picking (for refinements) at inflection point tangent/trough/peak
2. Export updated SEGY file

**Comment by DaloroAT** [comment]
Thank you for your feedback. I added them to the backlog.

Have you tried to pick your borehole data with the model?

**Comment by HHTC0** [comment]
Great, thanks. 

Yes, I ran it on VSP data and it did work. I am yet to test the parameters but overall result wasn’t bad. Having ability to tweak the time picks would be really beneficial.

**Comment by DaloroAT** [comment]
Ok. Let me know if you need help tuning the parameters. You can create a new issue and attach a screenshot with part of your data.

**Comment by HHTC0** [comment]
Ok. I will be doing further testing tomorrow.
