### ISSUE TITLE
didn't understand how to pick first break?

### ISSUE THREAD

**Issue by ad1995-geek** [DaloroAT/first_break_picking#2]
could you help me out , how to pick first break? I have read all of the codes. but only functions are defined. Didn't understand what are the functions are to be called ?

**Comment by DaloroAT** [comment]
Yes, of course.

First breaks are calculated during training to keep track of metrics. This is done using function [here](https://github.com/DaloroAT/first_break_picking/blob/a45bb007140f6011cf04ebe27a86eea8deb5e6eb/code/trainer.py#L126). This function does several calculations based on the last layer's featuremap.

To get a vector with the values of the first breaks, use [this function](https://github.com/DaloroAT/first_break_picking/blob/a45bb007140f6011cf04ebe27a86eea8deb5e6eb/code/metrics.py#L42).

**Comment by poprafka** [comment]
Hi DaloroAT, really interesting code and a nice readme! However, I'd like to add a vote to a better documentation and how to use/test the code. An example code introducing and demonstrating the expected input for the individual steps would be very appreciated.

**Comment by DaloroAT** [comment]
Hi @poprafka . Nice to hear that someone is interested in improving the project. In fact, I did this project when I wanted to go into deep learning, it was part of my CV. The last commit was more than two years ago when I was hired))

If you need usage documentation, I'll add it as soon as free time becomes available.

Also I continue the idea of ​​this project in a private repository. It changed the architecture, the network was trained on real data, and a FastAPI web server was also written to serve the model. If you are interested, write to `at.daloro@gmail.com`.

**Comment by HHTC0** [comment]
Hi, thank you for the code. As you mentioned above, did you had a chance to write down document on how to use the code?

**Comment by DaloroAT** [comment]
Hello @ad1995-geek @poprafka @HHTC0 !
I've finally updated the repo, added tutorials and model weights, and released new features.

You can find updates on two URLs:
https://github.com/DaloroAT/first_breaks_picking
https://pypi.org/project/first-breaks-picking/
