### ISSUE TITLE
Check manual picking

### ISSUE THREAD

**Issue by DaloroAT** [DaloroAT/first_break_picking#21]
Hi @HHTC0. 

I added the ability to refine the first breaks manually and export the pick to SGY. Could you check it?

**Comment by HHTC0** [comment]
@DaloroAT I spent sometime on this today. Updating to the versions of library and followed new requirements but stumbled upon same error which previously appeared when requirements were not met. Does it require any specific version of python too?

setWidth(self, width: int): argument 1 has unexpected type 'float

**Comment by DaloroAT** [comment]
So, in this case, you know what to do.

- Create fresh environments and use `pip install -U first-breaks-picking`.
- Create fresh environments and install packages with versions according to requirements [here](https://github.com/DaloroAT/first_breaks_picking/blob/main/requirements/basic.txt) and [here](https://github.com/DaloroAT/first_breaks_picking/blob/main/requirements/cpu.txt).

**Comment by DaloroAT** [comment]
The first way is preferred, because you will install the exact list of dependencies with fixed versions.

**Comment by DaloroAT** [comment]
If you followed the first way and it doesn't work, please type `pip list > installed_packages.txt` and send me created file.

**Comment by HHTC0** [comment]
Thank you for detailed instructions. I have created fresh environment in Anaconda and did install all the required packages. Sadly, the outcome remains the same with the same error.

Using Python 3.10.11 I have attached the installed package list.

[installed_packages.txt](https://github.com/DaloroAT/first_breaks_picking/files/11829353/installed_packages.txt)

Regards

**Comment by HHTC0** [comment]
I don't see update in GUI, does it look correct to you?

![Screenshot 2023-06-22 140826](https://github.com/DaloroAT/first_breaks_picking/assets/116859367/941bb052-8693-47af-9982-51afa19ba8c0)

**Comment by DaloroAT** [comment]
I am very sorry that the package cannot be delivered 😞 

Could you try installing using Python 3.8? This version should definitely work.

**Comment by HHTC0** [comment]
Right, 3.8.16 worked. Thanks

I did some automated and manual picking (love it!) on the same gather that you have provided.

Once opened the Exported SEGY in SeisSee (free software to view seismic) I could not find the headers values saved in it. The time header values should be saved in exported file, with accuracy of 3 decimal places. These are typically store in 2 digital integer bytes (105-106, 107-108). Also, it is important that all headers which are loaded should also be exported as it is without rounding off.

Overall, I really like the ease of refining time picking with such an ease. Thank you for sharing your good work with us.

**Comment by HHTC0** [comment]
Also, would be great, if the interface has the functionality of viewing the current time picks of raw loaded file (before automated time picking). Having an option to ON/OFF display of time picks would be helpful.

**Comment by HHTC0** [comment]
Additionally, having amplitude scaling options (gather normalize or trace by trace normalized) for correctly displaying the data for manual time picking would also be required. 

The trace spacing adjustment (very important for Borehole Seismic data) according to header values would be really helpful here. These values come from depth headers and are located in trace header byte 37-40 and 41-44. Thanks again!

**Comment by DaloroAT** [comment]
> Once opened the Exported SEGY in SeisSee (free software to view seismic) I could not find the headers values saved in it.

Previously I only used ZondST2D for picking and performing tomography. This package expects picking in [such format](https://github.com/DaloroAT/first_breaks_picking#save-results). If you are able to change the way how to decode headers, you can try to follow the current schema.

But of course, I should provide the possibility to setup how to store first breaks. I will do it next iteration.

**Comment by DaloroAT** [comment]
@HHTC0 

I created new issues based on your feedback. You can visit them and add more details if you want:

https://github.com/DaloroAT/first_breaks_picking/issues/23
https://github.com/DaloroAT/first_breaks_picking/issues/24
https://github.com/DaloroAT/first_breaks_picking/issues/25
https://github.com/DaloroAT/first_breaks_picking/issues/26

Feel free to create new issues if you'd like to see something in the app.

**Comment by DaloroAT** [comment]
Btw, do you have GPU from NVIDIA?

**Comment by HHTC0** [comment]
No, I don't.

**Comment by HHTC0** [comment]
> @HHTC0
> 
> I created new issues based on your feedback. You can visit them and add more details if you want:
> 
> #23 #24 #25 #26
> 
> Feel free to create new issues if you'd like to see something in the app.

Thank you...really appreciate.
