### ISSUE TITLE
Add the possibility to setup how to save first breaks in headers (byte, encoding, units)

### ISSUE THREAD

**Issue by DaloroAT** [DaloroAT/first_break_picking#23]
Feature request described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602099563

Right now `They are stored in the last 4 bytes (236 byte if counting from 0) to be decoded as an unsigned integer. Values are in microseconds.`

**Comment by HHTC0** [comment]
Did you millisecond?

**Comment by HHTC0** [comment]
Hi, can you please let me know if I am missing something here? I have mapped byte 236-239 but the values seems quite off and I could not work out conversion. Though the values in ascii file looks correct in ms.

![Timebreaks](https://github.com/DaloroAT/first_breaks_picking/assets/116859367/65273897-ece6-467a-b69a-eb6cc0c4b386)

**Comment by DaloroAT** [comment]
Hi @HHTC0 .
Position 236  if counting is started from 0. But SeiSee starts counting from 1. 

![image](https://github.com/DaloroAT/first_breaks_picking/assets/43877180/8b58e774-ecb7-460d-b94a-b2b523a14944)

So you need to get 237-240 bytes.

![image](https://github.com/DaloroAT/first_breaks_picking/assets/43877180/88dbc266-b7f4-4db9-9a0d-73d1327565a0)

Values in MCS are very similar to values in the app.

![image](https://github.com/DaloroAT/first_breaks_picking/assets/43877180/9b42402a-e539-4310-8743-34c6d49f2e83)
