### ISSUE TITLE
Add different scaling options

### ISSUE THREAD

**Issue by DaloroAT** [DaloroAT/first_break_picking#25]
Described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602121125

**Comment by HHTC0** [comment]
@DaloroAT currently the gain is starting from 0.1. Can we start it 0.01? At time dealing with data with high gain already applied, makes it hard to adjust the scaling.

**Comment by HHTC0** [comment]
Bug - If the scaling is adjusted after manual time picking already performed. The timepicks revert back to default values.

**Comment by DaloroAT** [comment]
> Bug - If the scaling is adjusted after manual time picking already performed. The timepicks revert back to default values.

I will check it

**Comment by DaloroAT** [comment]
> currently the gain is starting from 0.1. Can we start it 0.01?

Yes, we can, but I think it's difficult to precisely set values if we work with a range with several magnitudes. 
I think I can do similar to SeiSee, when you can scroll without borders and your slider moves to the center after releasing the mouse.

**Comment by HHTC0** [comment]
That’s good idea! Other possible solution could be to allow user to input number directly.

**Comment by HHTC0** [comment]
@DaloroAT Sorry but is it possible to get this one done by tomorrow if you have time?

**Comment by DaloroAT** [comment]
Hey @HHTC0 
Nope, it's not possible to **exactly** implement the way that we discussed above with auto-adjusting the slider to the current range tomorrow. 

But tomorrow I can replace sliders with a widget to input the exact value of gain and clip (like `Traces per gather` and `Maximum time` fields). Is it ok? I think it covers any wishes related to clip and gain as a temporal solution. And probably it's even better than adjusting the slider 😁

**Comment by HHTC0** [comment]
@DaloroAT Agree, it is actually simpler and much better solution. Would be great if I can have it by tomorrow. Thank you!

**Comment by DaloroAT** [comment]
Btw, on previous weekends I found a way to share the desktop app via zip with the `.exe` file. Are you interested in such a way to share the app? You don't need to have a python or install other libs with pip. Just this archive.

**Comment by DaloroAT** [comment]
@HHTC0 I finished this request. Do you need something else today? Otherwise, I can publish just this update.

**Comment by DaloroAT** [comment]
@HHTC0 
`pip install first-breaks-picking==0.3.1a0`

**Comment by HHTC0** [comment]
@DaloroAT sweet! I was so busy that I completely missed you timely messages. Its working perfectly with much ease.

Yeah having a desktop app would be beneficial. Can you please share more details.

Is it possible to allow editing of loaded time picks?

**Comment by DaloroAT** [comment]
> Yeah having a desktop app would be beneficial. Can you please share more details.

I'm working on it. It will be available in `Release` section of the project. I will let you know

> Is it possible to allow editing of loaded time picks?

Nope. Please, let's discuss it in dedicated issues not to miss it later

**Comment by DaloroAT** [comment]
@HHTC0 
Now you can also check new updates here:
https://github.com/DaloroAT/first_breaks_picking/releases

You can try to download [FirstBreaksPicking-0.5.1.zip](https://github.com/DaloroAT/first_breaks_picking/releases/download/v0.5.1/FirstBreaksPicking-0.5.1.zip), unzip it and launch `FirstBreaksPicking.exe`.

**Comment by HHTC0** [comment]
Thanks, the executable works well. However, trace numbers are not annotated for last levels. See attached.
![TraceNumbers](https://github.com/DaloroAT/first_breaks_picking/assets/116859367/b16691b5-8954-4258-9f74-5c8753098e64)


Regards

**Comment by HHTC0** [comment]
@DaloroAT thanks mate!
