### ISSUE TITLE
Show info about spatial positions for traces

### ISSUE THREAD

**Issue by DaloroAT** [DaloroAT/first_break_picking#26]
Described here

https://github.com/DaloroAT/first_breaks_picking/issues/21#issuecomment-1602121125

**Comment by DaloroAT** [comment]
Hey @HHTC0

Could you please send me a small SEGY file of your data with filled headers? I want to be sure that trace labels are displayed correctly.

**Comment by DaloroAT** [comment]
It's just about 24 or 48 traces.

If you don't want to publish it here, you can send me by e-mail. You can find it [here](https://github.com/DaloroAT/first_breaks_picking/blob/00bccf5f37bb9c8c40a594e13e3e2ea739d3dc6c/setup.py#L36).

**Comment by HHTC0** [comment]
Hi, I could not share with you my own data due to confidentiality reasons. However, here is some synthetic VSP data available on another project within GitHub.

[https://github.com/ajcampbell25/VSP_Basics/tree/master/data](url)
