### ISSUE TITLE
I have a qustion about first_break_picking

### ISSUE THREAD

**Issue by zhangxiaoshuotttt** [DaloroAT/first_break_picking#3]
I'm a beginner in deep learning.My data is in IBM format.I got a error when I used 'sgy reader.py' to read my data.Could you teach me how to use your program in my real data?I want to get the time of firs break.Thanks!

**Comment by DaloroAT** [comment]
Hey @zhangxiaoshuotttt 

Unfortunately, it is not able to read IBM format with the current reader, but I wrote code for this in my private snippets.
Anyway, I decided to update the project's codebase. I want to update the code and add the ability for a quick and understandable launch. But it won't be a quick process. 
I will tag you if you are still interested in this repo.

**Comment by zhangxiaoshuotttt** [comment]
Thanks,your code is very helpful to me.

**Comment by DaloroAT** [comment]
Hello @zhangxiaoshuotttt !
I've finally updated the repo, added tutorials and model weights, and released new features.

You can find updates on two URLs:
https://github.com/DaloroAT/first_breaks_picking
https://pypi.org/project/first-breaks-picking/

**Comment by zhangxiaoshuotttt** [comment]
Hi DaloroAT：

Thank you so much for getting back to me and sharing the updates. I really appreciate your help and will definitely check out the new features. Thanks again!
