### ISSUE TITLE
How to install this

### ISSUE THREAD

**Issue by satishgc227** [DaloroAT/first_break_picking#8]

**Comment by DaloroAT** [comment]
Hello @satishgc227 
I decided to update the project's codebase. I want to update the code and add the ability for a quick and understandable launch. I'll tag you when everything is ready. But it won't be a quick process.

**Comment by satishgc227** [comment]
Sir approximately how much time it will take sir.

**Comment by DaloroAT** [comment]
I'm not sure about the exact time, but right now I have my personal small server with a launched web application for picking. So my first steps are writing web UI with `streamlit` and a local app with PyQt. 

So If you just need to process your data without any extra training, these steps will cover your wishes.

**Comment by satishgc227** [comment]
Sir i want model built and also testing .But i am unable to figure out the
exact codung prt for the segy file.

**Comment by satishgc227** [comment]
Sir if possible can you plz share that streamlit built ui for picking bcz
atleast i will be able to get idea.Bcz i am unble to get anything on github
clearly.

**Comment by DaloroAT** [comment]
Ok, I will tag you, when `streamlit` will be ready

**Comment by satishgc227** [comment]
Sir like approximately how much time.

**Comment by DaloroAT** [comment]
I'm not sure about the time to finish, but the minimal time is 1 week.

**Comment by satishgc227** [comment]
Sure sir then.

**Comment by satishgc227** [comment]
Sir if possible  plz give me the things that are done atleast for just
visualization of first break picking.

**Comment by satishgc227** [comment]
Respected sir,
             When we will be able to get the entire application of first break picking using streamlit.

**Comment by DaloroAT** [comment]
Dear @satishgc227 
What do you mean by `entire application`? I can only provide web UI, where you will upload your SGY, wait some time, and receive positions of first breaks as `txt` file.

**Comment by satishgc227** [comment]
Yes sir i meant application for break picking only sir.

**Comment by DaloroAT** [comment]
I just wanted to clarify one moment. If you worry about the privacy of your data, don't want to share it outside your company, and want to launch a project inside your company - it will not be possible.

**Comment by satishgc227** [comment]
Sir, it is general available data that is being used for analysis from net
segy data.

**Comment by DaloroAT** [comment]
Ok, no problem for general available data. 

I need time to write `streamlit` app. But if you want to use the service as soon as possible, I can provide you python snippets, on how to communicate with the server.

**Comment by DaloroAT** [comment]
Do you have messengers like `telegram` or `whatsapp`?

**Comment by DaloroAT** [comment]
You also can write to my mail `at.daloro@gmail.com`. I don't want to share snippets via GitHub.

**Comment by satishgc227** [comment]
Sir i had written mail to your mail id.kindly check

Regards.

**Comment by sukilove** [comment]
> 我不确定确切的时间，但现在我有我的个人小型服务器，其中有一个已启动的 Web 应用程序可供选择。所以我的第一步是`streamlit`使用 PyQt 编写 Web UI 和本地应用程序。
> 
> 因此，如果您只需要处理您的数据而无需任何额外培训，这些步骤将满足您的愿望。



> Ok, no problem for general available data.
> 
> I need time to write `streamlit` app. But if you want to use the service as soon as possible, I can provide you python snippets, on how to communicate with the server.


> Dear @satishgc227 What do you mean by `entire application`? I can only provide web UI, where you will upload your SGY, wait some time, and receive positions of first breaks as `txt` file.

Can you provide me with your web link to access it

**Comment by DaloroAT** [comment]
Hello @satishgc227 , @sukilove !
I've finally updated the repo, added tutorials and model weights, and released new features.

You can find updates on two URLs:
https://github.com/DaloroAT/first_breaks_picking
https://pypi.org/project/first-breaks-picking/
