### ISSUE TITLE
Request for the examples/tutorials

### ISSUE THREAD

**Issue by kerim371** [DaloroAT/first_break_picking#9]
Hi,

I would like to try this package but it is difficult to start.

Is there any examples how to use it? Especially I'm looking for the python commands...

**Comment by DaloroAT** [comment]
Hi @kerim371 

I decided to update the project's codebase. I want to update the code and add the ability for a quick and understandable launch. But it won't be a quick process. I will tag you if you are still interested in this repo.

**Comment by kerim371** [comment]
@DaloroAT yes thank you, it would be nice

**Comment by DaloroAT** [comment]
Hello @kerim371!
I've finally updated the repo, added tutorials and model weights, and released new features.

You can find updates on two URLs:
https://github.com/DaloroAT/first_breaks_picking
https://pypi.org/project/first-breaks-picking/

**Comment by kerim371** [comment]
Hi,

Thank you very much!
I will test it soon.

**Comment by kerim371** [comment]
@DaloroAT I'm starting testing it.

I'm not good at AI but could you please explain may I use the same model for different SEGY? I guess the model is trained on some data and it should be applyiable to different SEGY.
But currently I tried to test it with my modeled data (61 traces per shot) and it runs not good.
Do I need to somehow train model?

P.S. I started from GUI app.

![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/93ac6a6b-0260-4576-beea-36369c45e6b1)

**Comment by DaloroAT** [comment]
Yes, you are right, it should work for different sgy. But the model will works good if your data have "similar distributions". In case of picking first breaks, the waveform of first wave should be similar to the waveform of train data. In real data the first wave usually has shorter length and lower amplitude (or similar) in comparison to the next waves, but in your example situation is opposite and looks non realistic. You can try to add noise or generate another synthetic example if it's possible. Let me know if it helps.

Thank you for notice, definitely i should add synthetic examples to train dataset to avoid it in the future!

**Comment by kerim371** [comment]
@DaloroAT I added some gaussian noise.
These are my first tests. The goal is to understand how to effectively use with field data.

![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/752f6edc-71a7-4dbd-9daf-64e1299c73a6)

**Comment by kerim371** [comment]
Spectrum of a `real_gather.sgy` that comes with `first_breaks_picks` package:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/628f6c0f-b9cd-4e17-a381-25a610d90bf9)

Spectrum of my synthetic data:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/fabc885d-75f9-45f2-8c5c-83e991625cd8)

**Comment by kerim371** [comment]
Just tried on real marine data:
![image](https://github.com/DaloroAT/first_breaks_picking/assets/43808863/f337e8cc-606b-4590-81fd-75acd5342996)

**Comment by DaloroAT** [comment]
@kerim371 Let's go to discuss in new issue 

https://github.com/DaloroAT/first_breaks_picking/issues/14
